#!/bin/bash
set -eu
source /usr/share/yunohost/helpers

ynh_systemd_action --service_name="$app" --action="stop" --log_path="systemd" || true
ynh_safe_rm "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_safe_rm "/etc/systemd/system/$app.service"
systemctl daemon-reload
