#!/bin/bash
set -eu
source "$(dirname "$0")/_common.sh"

source_root="$(package_root)"
ynh_backup_before_upgrade
ynh_systemd_action --service_name="$app" --action="stop" --log_path="systemd"
cp -a "$source_root/gratitude_app/." "$install_dir/gratitude_app/"
chown -R "$app:$app" "$install_dir"
ynh_config_add --template="nginx.conf" --destination="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_config_add --template="gratitude.service" --destination="/etc/systemd/system/$app.service"
systemctl daemon-reload
ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd"
